from beanie import Document
from pydantic import BaseModel
from app.core.config import settings
from beanie import PydanticObjectId

class Group(Document):
    # group id is autogenerated by beanie
    user_id: PydanticObjectId
    name: str = "default"

    class Settings:
        name = settings.GROUP_COLLECTION_NAME
        indexes = ["user_id", [("last_updated", -1)]]
